/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RaboForm {
    }
    interface RaboMoneyInput {
    }
    interface RaboRoot {
    }
}
declare global {
    interface HTMLRaboFormElement extends Components.RaboForm, HTMLStencilElement {
    }
    var HTMLRaboFormElement: {
        prototype: HTMLRaboFormElement;
        new (): HTMLRaboFormElement;
    };
    interface HTMLRaboMoneyInputElement extends Components.RaboMoneyInput, HTMLStencilElement {
    }
    var HTMLRaboMoneyInputElement: {
        prototype: HTMLRaboMoneyInputElement;
        new (): HTMLRaboMoneyInputElement;
    };
    interface HTMLRaboRootElement extends Components.RaboRoot, HTMLStencilElement {
    }
    var HTMLRaboRootElement: {
        prototype: HTMLRaboRootElement;
        new (): HTMLRaboRootElement;
    };
    interface HTMLElementTagNameMap {
        "rabo-form": HTMLRaboFormElement;
        "rabo-money-input": HTMLRaboMoneyInputElement;
        "rabo-root": HTMLRaboRootElement;
    }
}
declare namespace LocalJSX {
    interface RaboForm {
    }
    interface RaboMoneyInput {
    }
    interface RaboRoot {
    }
    interface IntrinsicElements {
        "rabo-form": RaboForm;
        "rabo-money-input": RaboMoneyInput;
        "rabo-root": RaboRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rabo-form": LocalJSX.RaboForm & JSXBase.HTMLAttributes<HTMLRaboFormElement>;
            "rabo-money-input": LocalJSX.RaboMoneyInput & JSXBase.HTMLAttributes<HTMLRaboMoneyInputElement>;
            "rabo-root": LocalJSX.RaboRoot & JSXBase.HTMLAttributes<HTMLRaboRootElement>;
        }
    }
}
