/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MoneyInputAmount } from "./core/interfaces/money-input.interface";
export namespace Components {
    interface MoneyInput2 {
    }
    interface RaboForm {
    }
    interface RaboMoneyInput {
    }
    interface RaboRoot {
    }
}
declare global {
    interface HTMLMoneyInput2Element extends Components.MoneyInput2, HTMLStencilElement {
    }
    var HTMLMoneyInput2Element: {
        prototype: HTMLMoneyInput2Element;
        new (): HTMLMoneyInput2Element;
    };
    interface HTMLRaboFormElement extends Components.RaboForm, HTMLStencilElement {
    }
    var HTMLRaboFormElement: {
        prototype: HTMLRaboFormElement;
        new (): HTMLRaboFormElement;
    };
    interface HTMLRaboMoneyInputElement extends Components.RaboMoneyInput, HTMLStencilElement {
    }
    var HTMLRaboMoneyInputElement: {
        prototype: HTMLRaboMoneyInputElement;
        new (): HTMLRaboMoneyInputElement;
    };
    interface HTMLRaboRootElement extends Components.RaboRoot, HTMLStencilElement {
    }
    var HTMLRaboRootElement: {
        prototype: HTMLRaboRootElement;
        new (): HTMLRaboRootElement;
    };
    interface HTMLElementTagNameMap {
        "money-input-2": HTMLMoneyInput2Element;
        "rabo-form": HTMLRaboFormElement;
        "rabo-money-input": HTMLRaboMoneyInputElement;
        "rabo-root": HTMLRaboRootElement;
    }
}
declare namespace LocalJSX {
    interface MoneyInput2 {
    }
    interface RaboForm {
    }
    interface RaboMoneyInput {
        "onChanged"?: (event: CustomEvent<MoneyInputAmount>) => void;
    }
    interface RaboRoot {
    }
    interface IntrinsicElements {
        "money-input-2": MoneyInput2;
        "rabo-form": RaboForm;
        "rabo-money-input": RaboMoneyInput;
        "rabo-root": RaboRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "money-input-2": LocalJSX.MoneyInput2 & JSXBase.HTMLAttributes<HTMLMoneyInput2Element>;
            "rabo-form": LocalJSX.RaboForm & JSXBase.HTMLAttributes<HTMLRaboFormElement>;
            "rabo-money-input": LocalJSX.RaboMoneyInput & JSXBase.HTMLAttributes<HTMLRaboMoneyInputElement>;
            "rabo-root": LocalJSX.RaboRoot & JSXBase.HTMLAttributes<HTMLRaboRootElement>;
        }
    }
}
